//
//  SwipeableCalendarView.swift
//  FitSenpai
//
//  Created by Mark Daquis on 4/8/25.
//

import SwiftUI

// import YourModuleContainingCalendarDataManager

struct SwipeableCalendarView: View {

    @StateObject private var calendarManager = CalendarDataManager.shared
    
    @State var shouldShowWeekView = true // Local UI state, can remain

    var body: some View {
        VStack {
            // Week Range
            HStack(alignment: .center) {
                FSText(text: weekRangeText, fontStyle: .medium14, color: .fsMutedForeground)
                    .padding(.leading, 12)
                
                Spacer()
            }
            
            if shouldShowWeekView {
                // This ensures this view doesn't show future weeks even if the manager allows them.
                let displayMaximumWeekOffset = min(calendarManager.computedMaximumWeekOffset, 0)

                // Swipeable Weeks
                TabView(selection: $calendarManager.currentWeekOffset) {
                    if calendarManager.computedMinimumWeekOffset <= displayMaximumWeekOffset {
                        ForEach(calendarManager.computedMinimumWeekOffset...displayMaximumWeekOffset, id: \.self) { offset in
                        // NOTE: WeekView has its own CalendarDataManager.
                            // The call should only include 'weekOffset'.
                            WeekView(
                                weekOffset: offset
                            )
                            .tag(offset)
                        }
                    } else {
                        // This block will be entered if computedMinimumWeekOffset > displayMaximumWeekOffset.
                        // For example, if startDate is in the future (minOffset > 0) and displayMax is 0.
                        // In this case, no pages should be generated by ForEach, which is correct.
                        // The TabView will be empty or show its default behavior for no pages.
                    }
                }
                .tabViewStyle(.page(indexDisplayMode: .never))
            }
        }
        .frame(height: shouldShowWeekView ? 90 : 30)
        .padding(.horizontal, 12)
    }

    // MARK: - Helper Functions
    
    // These are now in CalendarDataManager or accessed via it.
    
    private var weekRangeText: String {
        let weekDates = calendarManager.daysInWeek(for: calendarManager.currentWeekOffset)
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMMM"
        
        // let dateFormatter2 = DateFormatter()
        // dateFormatter2.dateFormat = " d"
        
        guard let start = weekDates.first else { return "" } // Simplified: was checking weekDates.last but not using it
        
        return "\(dateFormatter.string(from: start))"
    }
}

struct SwipeableCalendarView_Previews: PreviewProvider {
    static var previews: some View {
        let manager = CalendarDataManager.shared
        // Example: Configure manager to allow future dates (e.g., for testing)
        // manager.configure(
        //     startDate: Date(),
        //     endDate: Calendar.current.date(byAdding: .weekOfYear, value: 5, to: Date())!, // 5 weeks in future
        //     initialSelectedDate: Date(),
        //     initialWeekOffset: 0
        // )

        // Example: Configure manager to restrict future dates (endDate is today)
        manager.configure(
            startDate: Calendar.current.date(byAdding: .weekOfYear, value: -4, to: Date())!, // 4 weeks in past
            endDate: Date(), // End date is today
            initialSelectedDate: Date(),
            initialWeekOffset: 0
        )

        manager.progressData = [
            Date(): 0.5,
            Calendar.current.date(byAdding: .day, value: 2, to: Date())!: 0.3,
            Calendar.current.date(byAdding: .day, value: 4, to: Date())!: 0.8,
            Calendar.current.date(byAdding: .day, value: 5, to: Date())!: 0.1,
            Calendar.current.date(byAdding: .day, value: 6, to: Date())!: 0.3,
            Calendar.current.date(byAdding: .day, value: 7, to: Date())!: 0.7,
            Calendar.current.date(byAdding: .day, value: 8, to: Date())!: 0.9
        ]
        manager.highlightedDays = [1,3,5]

        return SwipeableCalendarView()
    }
}
